name: publish pages

on:
  push:
    branches:
      - "docs"

jobs:
  build:
    name: publish pages
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{secrets.PAT}}
          ref: "docs"

      - name: publish to gh-pages
        run: |
          git checkout -b gh-pages
          git push --set-upstream origin gh-pages --force
