name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Lean
        uses: leanprover/lean-action@v1
        with:
          test: false
          lint: false
          use-github-cache: true

      - name: Build Docs
        working-directory: docs
        run: |
          lake update
          lake build UnicodeDocs:docs

      - name: Compress Docs
        working-directory: docs/.lake/build
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: |
          tar -czf ../../docs-${TAG_NAME}.tar.gz doc doc-data
          zip -rq ../../docs-${TAG_NAME}.zip doc doc-data

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            docs/docs-${{ github.ref_name }}.tar.gz
            docs/docs-${{ github.ref_name }}.zip
          fail_on_unmatched_files: true
